server:
  port: 8084

spring:
  application:
    name: gateway
  # Config server
  config:
    import: optional:configserver:http://config-server-ms:8080
  profiles:
    active: dev
  # gateway
  cloud:
    gateway:
      routes:
        - id: review_service
          # container name: review
          uri: http://review:8081
          predicates:
            - Path=/reviews/**

        - id: job_service
          # container name: job
          uri: http://job:8082
          predicates:
            - Path=/jobs/**

        - id: company_service
          # container name: company
          uri: http://company:8083
          predicates:
            - Path=/companies/**

        - id: eureka-server
          uri: http://servicereg:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/

        - id: eureka-server-static
          uri: httpL//servicereg:8761
          predicates:
            - Path=/eureka/**
    metrics:
      enabled: true

logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO



# Zipkin
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://servicereg:8761/eureka/
    registry-with-eureka: true
    fetch-registry: true


