server:
  port: 8083

review-service:
  url: http://review:8081
job-service:
  url: http://job:8082
company-service:
  url: http://company:8083

spring:
  application:
    name: company-service
  h2:
    console:
      enabled: true
  # PostgreSQL
  datasource:
    url: jdbc:postgresql://postgres:5432/company
    username: admin
    password: 1234
  jpa:
    show:
      sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # Config server
  config:
    import: optional:configserver:http://config-server-ms:8080

  # RabbitMQ
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

# Zipkin
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://servicereg:8761/eureka/
    registry-with-eureka: true
    fetch-registry: true

