spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/J-Punnawich/microservice-config.git


# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://servicereg:8761/eureka/